let num = 20;
let str = "gaurav";
let bool = true;
let obj = {number : 40};
obj.firstname = "thorat";
let arr = [10, 20, 30];
console.log(typeof num);
console.log(typeof str);
console.log(typeof bool);
console.log(typeof obj);
console.log(typeof arr);
console.log(obj);
